import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ReduxProvider from "@/components/Provider/ReduxProvider";
import Session from "@/components/Provider/SessionProvider";
import UserProvider from "@/components/Provider/UserProvider";
import ToastProvider from "@/components/Provider/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HETTY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Session>
            <UserProvider>
              <Navbar />
              {children}
              <Footer />
              <ToastProvider />
            </UserProvider>
          </Session>
        </ReduxProvider>
      </body>
    </html>
  );
}
